workflows: 
  android-workflow: 
    name: Android Internal Testing Workflow
    environment: 
      flutter: stable
      groups: 
        - google_credentials
      xcode: latest
      cocoapods: default
    max_build_duration: 30
    scripts:
      - name: Setup the keystore
        script: | 
          echo $KEYSTORE_FILE | base64 --decode > /tmp/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/tmp/keystore.jks
          EOF
      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
          flutter build appbundle --release
    artifacts: 
      - build/**/outputs/**/*.aab
    publishing: 
      google_play: 
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
        submit_as_draft: true
  ios-workflow: 
    name: iOS Internal Testing with Testflight Workflow
    max_build_duration: 30
    integrations: 
      app_store_connect: MERTEN
    environment: 
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.parentia
    scripts:  
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles \
          --custom-export-options="{\"testFlightInternalTestingOnly\": true}"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release --export-options-plist=export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing: 
        app_store_connect: 
          auth: integration
          submit_to_testflight: true
          beta_groups: 
            - internal
          submit_to_app_store: false